name: Build Project

on: [push, pull_request]

jobs:
  build_job:
    name: Build
    runs-on: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: build
